import React, { useState, useEffect } from 'react';
const API_URL =
  import.meta.env.VITE_API_URL || "http://localhost:8000";
import{createRoot}from'react-dom/client';import{ShieldCheck,LayoutDashboard,Users,FileCheck,Clock3,AlertTriangle,Search,Eye,CheckCircle2,Database,IndianRupee,MessageCircle,BarChart3,Menu,X,LogOut,FileText,ChevronRight}from'lucide-react';import'./style.css';
const rows=[['ST-2026-10482','Post-Matric Scholarship','Document Verified','Low Risk'],['ST-2026-10319','Top Class Education','Institute Review','Review'],['ST-2026-10112','National Fellowship for ST','Sanction Ready','Verified'],['ST-2026-09981','Post-Matric Scholarship','Deficiency','Action']];
function App(){const[t,setT]=useState('overview');const nav=[['overview','Overview',LayoutDashboard],['applications','Applications',FileCheck],['verification','Verification Queue',Users],['payments','DBT / Payments',IndianRupee],['analytics','Analytics',BarChart3]];return <div className="app"><aside><div className="brand"><div className="mark"><ShieldCheck/></div><div><b>STSetu</b><small>Admin / Officer Portal</small></div></div><div className="admin"><div>HQ</div><span><b>Officer Demo</b><small>Ministry / State Authority</small></span></div>{nav.map(([id,n,I])=><button className={t===id?'active':''} onClick={()=>setT(id)} key={id}><I size={18}/>{n}</button>)}<div className="asidebottom"><div className="tech"><Database size={16}/><span><b>MOTA-aligned</b><small>FastAPI + React architecture</small></span></div><button><LogOut size={17}/>Sign out</button></div></aside><main><header><div><div className="eyebrow">MINISTRY OF TRIBAL AFFAIRS • STSETU</div><h1>{nav.find(x=>x[0]===t)?.[1]}</h1></div><div className="head"><span>SIH DEMO</span><button><MessageCircle size={17}/>JAGO AI</button></div></header>{t==='overview'&&<Overview/>}{t==='applications'&&<Applications/>}{t==='verification'&&<Verification/>}{t==='payments'&&<Payments/>}{t==='analytics'&&<Analytics/>}</main></div>}
const Card=({icon:Icon,label,value,sub})=><div className="card metric"><div className="metricicon"><Icon/></div><div><small>{label}</small><strong>{value}</strong><span>{sub}</span></div></div>;
function Overview(){return <><section className="welcome"><div><span>ADMINISTRATION OVERVIEW</span><h2>Unified scholarship operations at a glance.</h2><p>Monitor applications, automated verification, deficiencies, sanction readiness and DBT status from one officer portal.</p></div><ShieldCheck size={70}/></section><div className="metrics"><Card icon={Users} label="Total Applications" value="1,284" sub="Across demo schemes"/><Card icon={CheckCircle2} label="Verified" value="936" sub="73% processed"/><Card icon={Clock3} label="Pending Review" value="214" sub="Requires officer action"/><Card icon={AlertTriangle} label="Deficiency" value="134" sub="Student correction"/></div><div className="twocol"><div className="card"><Title text="Recent verification queue"/><Table compact/></div><div className="card"><Title text="System modules"/><ul className="modules"><li><CheckCircle2/>Eligibility & scheme engine</li><li><CheckCircle2/>Document verification / DigiLocker</li><li><CheckCircle2/>Conflict & deficiency handling</li><li><CheckCircle2/>DBT / payment tracking</li><li><CheckCircle2/>JAGO AI support</li></ul></div></div></>}
function Title({text}){return <div className="title"><b>{text}</b><button>View all <ChevronRight size={15}/></button></div>};function Table({compact=false}){return <div className="table"><div className="tr th"><span>Application</span><span>Scheme</span><span>Status</span><span>Risk</span><span></span></div>{rows.map(r=><div className="tr" key={r[0]}><span><b>{r[0]}</b><small>Today</small></span><span>{r[1]}</span><span><em>{r[2]}</em></span><span className="risk">{r[3]}</span><button><Eye size={16}/></button></div>)}</div>}
function Applications(){return <div className="card full"><Title text="Scholarship applications"/><div className="search"><Search size={17}/><input placeholder="Search application ID, student or scheme"/></div><Table/></div>}
function Verification(){return <div className="twocol"><div className="card"><Title text="Automated verification queue"/><Table/></div><div className="card"><Title text="Verification checks"/><div className="checklist"><div><CheckCircle2/>ST Certificate <b>Passed</b></div><div><CheckCircle2/>Income Certificate <b>Passed</b></div><div><CheckCircle2/>Academic Record <b>Passed</b></div><div><AlertTriangle/>Duplicate / conflict check <b>Clear</b></div></div><button className="primary"><FileCheck size={16}/> Open review workspace</button></div></div>}
function Payments(){return <><div className="metrics"><Card icon={IndianRupee} label="Sanction Ready" value="₹1.84 Cr" sub="Demo portfolio"/><Card icon={Clock3} label="DBT Processing" value="218" sub="Transactions"/><Card icon={CheckCircle2} label="Credited" value="1,012" sub="Completed"/><Card icon={AlertTriangle} label="Exceptions" value="19" sub="Requires review"/></div><div className="card"><Title text="DBT payment tracker"/><Table/></div></>}
function Analytics(){return <div className="twocol"><div className="card"><Title text="Scheme distribution"/><div className="bars">{[['Post-Matric',72],['Pre-Matric',46],['Top Class',34],['NFST',22],['NOS',14]].map(x=><div><span>{x[0]}</span><i style={{width:x[1]*1.05+'%'}}></i><b>{x[1]}%</b></div>)}</div></div><div className="card"><Title text="Technology & integrations"/><div className="modules"><li><CheckCircle2/>React + Vite officer portal</li><li><CheckCircle2/>FastAPI service layer</li><li><CheckCircle2/>SQLAlchemy / database-ready</li><li><CheckCircle2/>DigiLocker / verification-ready</li><li><CheckCircle2/>DBT / payment workflow</li></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
