import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,GraduationCap,FileCheck,Wallet,MessageCircle,User,ShieldCheck,ChevronRight,CheckCircle2,Clock3,AlertTriangle,Upload,Send,IndianRupee,Search,LogIn,Menu,X,BarChart3,Users,FileText,ArrowRight,Sparkles,Bell,FolderOpen,Database,RefreshCw,Eye,Check,ShieldAlert,Landmark,BookOpen,Globe2} from 'lucide-react';
import './style.css';

const schemes=[
{id:'post',name:'Post-Matric Scholarship',tag:'Higher Education',amount:'As per scheme guidelines',desc:'Financial assistance for eligible ST students pursuing post-matric education.'},
{id:'pre',name:'Pre-Matric Scholarship',tag:'Class IX–X',amount:'As per scheme guidelines',desc:'Support for eligible ST students studying in secondary classes.'},
{id:'top',name:'Top Class Education',tag:'Premier Institutes',amount:'As per scheme guidelines',desc:'Support for ST students admitted to notified premier institutions.'},
{id:'nfst',name:'National Fellowship for ST',tag:'Research / PhD',amount:'Fellowship support',desc:'Fellowship support for eligible ST research scholars.'},
{id:'nos',name:'National Overseas Scholarship',tag:'Study Abroad',amount:'As per scheme guidelines',desc:'Support for eligible ST students pursuing higher studies abroad.'}
];
const initialApps=[{id:'ST-2026-10482',scheme:'Post-Matric Scholarship',status:'Under Verification',date:'28 Sep 2026',amount:'₹48,000'}];
function App(){
 const [role,setRole]=useState('student'),[tab,setTab]=useState('dashboard'),[logged,setLogged]=useState(false),[apps,setApps]=useState(initialApps),[toast,setToast]=useState(''),[chat,setChat]=useState(false),[menu,setMenu]=useState(false),[digilocker,setDigi]=useState(false);
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const apply=s=>{if(s.id!=='post'){notify('Demo eligibility check: additional scheme criteria required.');return;} if(apps.some(a=>a.scheme===s.name)){notify('Existing application found for this scheme.');return;} const id='ST-2026-'+Math.floor(10000+Math.random()*89999);setApps([{id,scheme:s.name,status:'Submitted',date:'29 Sep 2026',amount:'₹48,000'},...apps]);setTab('applications');notify('Application submitted successfully.');};
 if(!logged)return <Login onLogin={()=>setLogged(true)}/>;
 if(role==='officer')return <Officer onBack={()=>setRole('student')}/>;
 const nav=[['dashboard','Dashboard',Home],['schemes','Scholarship Schemes',GraduationCap],['applications','Applications Track',FileCheck],['documents','Document Wallet',FolderOpen],['payments','Payment Tracker',Wallet],['notifications','Notifications',Bell],['profile','Profile',User]];
 return <div className="app"><header><div className="brand"><div className="brandmark"><ShieldCheck size={23}/></div><div><b>STSetu</b><span>Unified Scholarship Platform for ST Students</span></div></div><div className="head-actions"><span className="stack-badge">MOTA Prototype</span><button className="lang">हिंदी</button><button className="officer" onClick={()=>setRole('officer')}>Admin Dashboard</button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>{menu&&<div className="mobilemenu">{nav.map(([id,n,I])=><button key={id} onClick={()=>{setTab(id);setMenu(false)}}><I size={17}/>{n}</button>)}</div>}<main><aside><div className="userbox"><div className="avatar">HQ</div><div><b>Habibah Qamar</b><span>ST Student • MCA</span></div></div>{nav.map(([id,n,I])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}><I size={18}/>{n}</button>)}<div className="sidebottom"><div className="mini"><Sparkles size={16}/><span><b>JAGO AI</b><small>Scholarship guidance assistant</small></span></div><button onClick={()=>setChat(true)} className="chatbtn"><MessageCircle size={17}/>Ask JAGO AI</button></div></aside><section className="content">
 {tab==='dashboard'&&<Dashboard apps={apps} go={setTab} />}{tab==='schemes'&&<Schemes apply={apply}/>}{tab==='applications'&&<Applications apps={apps}/>} {tab==='documents'&&<Documents openDigi={()=>setDigi(true)}/>} {tab==='payments'&&<Payment/>}{tab==='notifications'&&<Notifications/>}{tab==='profile'&&<Profile/>}
 </section></main>{chat&&<Chat close={()=>setChat(false)}/>} {digilocker&&<DigiLocker close={()=>setDigi(false)} notify={notify}/>} {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</div>
}
function Login({onLogin}){return <div className="login"><div className="login-card"><div className="brand center"><div className="brandmark big"><ShieldCheck size={32}/></div><div><b>STSetu</b><span>Unified Scholarship Platform</span></div></div><div className="login-hero"><div className="eyebrow">MINISTRY OF TRIBAL AFFAIRS • SIH DEMO</div><h1>One portal for the <em>complete scholarship journey.</em></h1><p>Discover schemes, check eligibility, use the Document Wallet, track verification and monitor DBT in one unified workflow.</p></div><div className="demo-note"><Sparkles size={18}/><div><b>SIH Demonstration Mode</b><span>Prototype data only. DigiLocker, JAGO AI and DBT are simulated for demonstration.</span></div></div><button className="primary full" onClick={onLogin}><LogIn size={18}/>Enter Student Demo <ArrowRight size={18}/></button><small className="centertext">Built on the MOTA project technology direction • React + Vite + Tailwind + FastAPI architecture</small></div></div>}
function Dashboard({apps,go}){return <><div className="hero"><div><div className="eyebrow">STUDENT DASHBOARD</div><h1>Welcome to STSetu, Habibah.</h1><p>A unified journey from scholarship discovery and eligibility to document verification, sanction and Direct Benefit Transfer.</p><div className="hero-actions"><button className="primary" onClick={()=>go('schemes')}>Explore Scholarship Schemes <ArrowRight size={17}/></button><button className="secondary" onClick={()=>go('applications')}>Track Application</button></div></div><div className="hero-art"><ShieldCheck size={64}/><span>Unified<br/>Scholarship<br/>Journey</span></div></div><div className="sectionhead"><div><h2>Dashboard overview</h2><p>Current student application and service status</p></div></div><div className="stats"><Stat icon={GraduationCap} label="Scholarship Schemes" value="5"/><Stat icon={FileCheck} label="Active Applications" value={apps.length}/><Stat icon={FolderOpen} label="Documents Verified" value="3/3"/><Stat icon={Wallet} label="DBT Status" value="Processing"/></div><div className="grid2"><div className="panel"><div className="paneltitle"><span>Application status</span><button onClick={()=>go('applications')}>View details <ChevronRight size={15}/></button></div><div className="track"><div className="trackline"><i className="done"/><i className="done"/><i className="current"/><i/></div><div className="tracklabels"><span>Submitted</span><span>Documents</span><span>Verification</span><span>Sanction</span></div></div><div className="appref">{apps[0]?.id} <span>{apps[0]?.status}</span></div></div><div className="panel"><div className="paneltitle"><span>Integrated services</span></div><ul className="benefits"><li><CheckCircle2/>Eligibility & scholarship scheme discovery</li><li><CheckCircle2/>Document Wallet + DigiLocker simulation</li><li><CheckCircle2/>Conflict / duplicate application check</li><li><CheckCircle2/>JAGO AI guidance + DBT tracking</li></ul></div></div></>}
function Stat({icon:Icon,label,value}){return <div className="stat"><div className="staticon"><Icon size={19}/></div><div><small>{label}</small><b>{value}</b></div></div>}
function Schemes({apply}){return <><div className="pagehead"><div><div className="eyebrow">SCHOLARSHIP SCHEMES</div><h1>Unified scheme discovery</h1><p>Browse the five core scholarship schemes represented in the MOTA project.</p></div><div className="eligibility"><ShieldCheck size={19}/><span><b>Profile match:</b> ST • MCA • Demo income ₹2.1L</span></div></div><div className="search"><Search size={18}/><input placeholder="Search schemes, education level or scholarship..."/></div><div className="schemegrid">{schemes.map(s=><div className="scheme" key={s.id}><div className="scheme-top"><div className="schemeicon"><GraduationCap size={22}/></div><span className="pill">Scheme</span></div><div className="tag">{s.tag}</div><h3>{s.name}</h3><p>{s.desc}</p><div className="amount"><span>Assistance</span><b>{s.amount}</b></div><button className="primary full" onClick={()=>apply(s)}>Check Eligibility / Apply <ArrowRight size={16}/></button></div>)}</div></>}
function Applications({apps}){return <><div className="pagehead"><div><div className="eyebrow">APPLICATIONS TRACK</div><h1>Track application lifecycle</h1><p>Monitor submission, verification, sanction and DBT status.</p></div></div>{apps.map(a=><div className="panel application" key={a.id}><div className="apphead"><div><span className="tag">{a.scheme}</span><h3>{a.id}</h3><small>Submitted: {a.date}</small></div><span className="pill amber"><Clock3 size={14}/>{a.status}</span></div><div className="timeline"><Stage t="Application Submitted" done/><Stage t="Document Verification" done/><Stage t="Institute / State Verification" current/><Stage t="Sanction & DBT"/></div><div className="notice"><AlertTriangle size={17}/><span><b>Automated verification:</b> Core documents passed demo checks. Application is awaiting the next verification stage.</span></div></div>)}</>}
function Stage({t,done,current}){return <div className="stage"><div className={'stageicon '+(done?'done ':'')+(current?'current':'')}>{done?<CheckCircle2 size={16}/>:current?<Clock3 size={15}/>:<span>4</span>}</div><span>{t}</span></div>}
function Documents({openDigi}){const docs=[['ST Certificate','DigiLocker / Mock API','Verified'],['Income Certificate','Uploaded document','Verified'],['Marksheet','Uploaded document','Verified']];return <><div className="pagehead"><div><div className="eyebrow">DOCUMENT WALLET</div><h1>Verified document wallet</h1><p>Central place for scholarship documents and verification status.</p></div><button className="secondary" onClick={openDigi}><Database size={16}/> Connect DigiLocker</button></div><div className="doc-grid">{docs.map(([n,s,st])=><div className="panel doc" key={n}><div className="doc-icon"><FileText/></div><div><h3>{n}</h3><p>{s}</p><span className="verified"><Check size={13}/> {st}</span></div><button><Eye size={16}/></button></div>)}<div className="panel upload-card"><Upload size={25}/><h3>Upload a document</h3><p>Add a missing certificate for verification.</p><button className="secondary"><Upload size={15}/> Select file</button></div></div></>}
function DigiLocker({close,notify}){return <div className="modalwrap"><div className="modal"><div className="modalhead"><div><b>DigiLocker Integration</b><span>Mock gateway for SIH demonstration</span></div><button onClick={close}><X/></button></div><div className="digibox"><Database size={35}/><h3>Connect DigiLocker</h3><p>Fetch and verify selected certificates through the simulated central document vault.</p><button className="primary" onClick={()=>{notify('DigiLocker mock verification completed.');close()}}><ShieldCheck size={16}/> Verify & Fetch Documents</button></div></div></div>}
function Payment(){return <><div className="pagehead"><div><div className="eyebrow">PAYMENT TRACKER • DBT</div><h1>Direct Benefit Transfer status</h1><p>Transparent view of sanction and scholarship payment processing.</p></div></div><div className="paymentcard"><div className="payicon"><IndianRupee size={25}/></div><div><span>Post-Matric Scholarship</span><h2>₹48,000 <small>demo annual support</small></h2><div className="paystatus"><Clock3 size={15}/>DBT Processing</div></div><div className="account"><small>Destination account</small><b>XXXX XXXX 4821</b><span>Bank account verified</span></div></div><div className="grid2"><div className="panel"><div className="paneltitle"><span>Payment timeline</span></div><div className="simplelist"><div><CheckCircle2/>Sanction generated <span>Completed</span></div><div><CheckCircle2/>PFMS / DBT validation <span>Completed</span></div><div><Clock3/>Payment processing <span>In progress</span></div><div><Wallet/>Credit to student <span>Pending</span></div></div></div><div className="panel impact"><Landmark size={30}/><h3>Transparent scholarship delivery</h3><p>STSetu connects application status with a clear DBT journey so students can understand where their scholarship stands.</p></div></div></>}
function Notifications(){return <><div className="pagehead"><div><div className="eyebrow">NOTIFICATIONS</div><h1>Application updates</h1><p>Important alerts from the scholarship workflow.</p></div></div><div className="panel notice-list"><Notice icon={CheckCircle2} title="Documents verified" text="Your core scholarship documents passed the automated demo verification."/><Notice icon={Clock3} title="Application under verification" text="ST-2026-10482 is awaiting institute / state verification."/><Notice icon={ShieldAlert} title="No duplicate conflict detected" text="The demo conflict-prevention rule found no duplicate active scholarship application."/></div></>}
function Notice({icon:Icon,title,text}){return <div className="notification"><div className="nicon"><Icon size={18}/></div><div><b>{title}</b><p>{text}</p></div><small>Today</small></div>}
function Profile(){return <><div className="pagehead"><div><div className="eyebrow">STUDENT PROFILE</div><h1>Applicant profile</h1><p>Profile data used for eligibility and scholarship matching.</p></div></div><div className="profilegrid"><div className="panel profilehero"><div className="avatar large">HQ</div><h2>Habibah Qamar</h2><span>ST Student • MCA</span><div className="verified"><CheckCircle2 size={13}/> Profile verified</div></div><div className="panel details"><Field n="Student ID" v="STSETU-2026-10482"/><Field n="Category" v="Scheduled Tribe (ST)"/><Field n="Programme" v="Master of Computer Applications"/><Field n="Institution" v="KIPM College of Management"/><Field n="Family Income" v="₹2,10,000 / year"/><Field n="State" v="Uttar Pradesh"/></div></div></>}
function Field({n,v}){return <div className="field"><small>{n}</small><b>{v}</b></div>}
function Chat({close}){const [messages,setMessages]=useState([{who:'bot',t:'Namaste! I am JAGO AI. I can guide you on scholarship schemes, eligibility, documents and application status.'}]);const [input,setInput]=useState('');const send=()=>{if(!input.trim())return;const q=input;setMessages([...messages,{who:'you',t:q},{who:'bot',t:q.toLowerCase().includes('eligib')?'Based on the demo profile, Post-Matric Scholarship is available for an eligibility check. Please verify the scheme guidelines before submission.':'For this SIH prototype, I can explain schemes, required documents, application stages and DBT status.'}]);setInput('')};return <div className="chat"><div className="chathead"><div><b>JAGO AI</b><span>Scholarship Guidance Assistant • Demo</span></div><button onClick={close}><X size={17}/></button></div><div className="messages">{messages.map((m,i)=><div className={'bubble '+m.who} key={i}>{m.t}</div>)}</div><div className="chatinput"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask about scholarships..."/><button onClick={send}><Send size={15}/></button></div></div>}
function Officer({onBack}){const rows=[['ST-2026-10482','Post-Matric','Document Verified','Low Risk'],['ST-2026-10319','Top Class','Institute Review','Review'],['ST-2026-10112','NFST','Sanction Ready','Verified'],['ST-2026-09981','Post-Matric','Deficiency','Action']];return <div className="officerapp"><header><div className="brand"><div className="brandmark"><ShieldCheck size={23}/></div><div><b>STSetu</b><span>Admin / Officer Dashboard</span></div></div><button className="secondary" onClick={onBack}>← Student Portal</button></header><main className="offmain"><div className="pagehead"><div><div className="eyebrow">ADMIN DASHBOARD</div><h1>Scholarship administration overview</h1><p>Demo view for screening, verification and application analytics.</p></div></div><div className="stats"><Stat icon={Users} label="Total Applications" value="1,284"/><Stat icon={CheckCircle2} label="Verified" value="936"/><Stat icon={Clock3} label="Pending Review" value="214"/><Stat icon={AlertTriangle} label="Deficiency" value="134"/></div><div className="grid2"><div className="panel"><div className="paneltitle"><span>Verification queue</span><span className="pill green">Live Demo</span></div><div className="queue">{rows.map((r,i)=><div key={r[0]}><b>{i+1}</b><span>{r[0]}<small>{r[1]}</small></span><span>{r[2]}</span><button>{r[3]}</button></div>)}</div></div><div className="panel"><div className="paneltitle"><span>System modules</span></div><ul className="benefits"><li><CheckCircle2/>Eligibility & scheme engine</li><li><CheckCircle2/>Document verification / DigiLocker</li><li><CheckCircle2/>Conflict & deficiency handling</li><li><CheckCircle2/>DBT / payment tracking</li><li><CheckCircle2/>JAGO AI support</li></ul></div></div></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
